name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' # Sincronizamos con la versión de Azure

      - name: Build and Package
        run: |
          cd backend
          npm ci # Instalación limpia y rápida
          npx nest build # Compilación

          # PREPARAR CARPETA DE SALIDA (Para evitar errores de rutas en Azure)
          mkdir -p ../output
          cp -r dist/* ../output/
          cp package.json ../output/
          cp package-lock.json ../output/
          cd ../output
          npm install --production # Solo librerías de ejecución

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mayarch'
          slot-name: 'Production'
          package: output
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHProfile_38FAD546A00C49C69E883B2D5B3E0A95 }}
